### ISSUE TITLE
Can we use magclass::write.report? 

### ISSUE THREAD

**Issue by johanneskoch94** [pik-piam/rmndt#1]
`fwrite` and `magclass::write.report` produce different outputs (precision wise, and white-space wise, I think). 
This leads to some weird differences when comparing the standard mif, and a policy_cost-adjusted mif, see below. Any chance we could use `magclass::write.report` here? 

https://github.com/pik-piam/rmndt/blob/692b5f28462cb60ea55b441b739d6fb31a585c09/R/helpers.R#L61

image shows diff with mif file after remind run in red and mif file after policy cost calculation in green

![image](https://user-images.githubusercontent.com/43963181/157642690-a8bb5663-5e52-4bab-8d07-592e51ec7f8b.png)
![image](https://user-images.githubusercontent.com/43963181/157654575-bf2e5dcf-28e8-4b70-beef-c2f7e1a66477.png)

**Comment by Loisel** [comment]
Yes I agree. We can also file a deprecation warning here to use write.report directly.
